In [16]:
# Import Libraries
import numpy as np
import pandas as pd
import os

In [17]:
## Set working directory
os.chdir('E:/CR2/Repos/TNC-Demand-Model-Southeast/')

In [18]:
## Read in Data
pickups = pd.read_csv('Cleaned_Inputs/Intermediate/fayette_linear_pickups.csv')
pickups.head()

,Unnamed: 0,origin,AM_PRED_PICKUPS,NT_PRED_PICKUPS,MD_PRED_PICKUPS,PM_PRED_PICKUPS,EV_PRED_PICKUPS,PRED_PICKUPS,NT_PRED_PICKUPS_LOG,AM_PRED_PICKUPS_LOG,MD_PRED_PICKUPS_LOG,PM_PRED_PICKUPS_LOG,EV_PRED_PICKUPS_LOG,PRED_PICKUPS_LOG
0,0,21067000101,115.549482,200.85,365.444593,275.623100,305.226973,1262.694147,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003
1,1,21067000102,51.240226,79.87,131.453742,93.462526,119.158567,475.185060,4.380400,3.936525,4.878655,4.537561,4.780455,6.163704
2,2,21067000200,31.729946,27.19,66.553038,41.892050,39.597918,206.962951,3.302849,3.457261,4.197999,3.735096,3.678777,5.332540
3,3,21067000300,26.862281,9.37,35.541701,16.881148,14.645182,103.300312,2.237513,3.290723,3.570707,2.826197,2.684111,4.637640
4,4,21067000400,17.330322,6.59,31.660462,20.130312,14.106015,89.817110,1.885553,2.852458,3.455069,3.002227,2.646601,4.497775

In [19]:
dest_choice = pd.read_csv('Cleaned_Inputs/Intermediate/dest_choice_prob_logsum.csv')
dest_choice.head()

,Unnamed: 0,origin,destination,dest_choice_logsum,NT_PROB,AM_PROB,MD_PROB,PM_PROB,EV_PROB,airport,tourist,MEDIAN_AGE,P_BACH_25P,TOTAL_EMP_DEN
0,0,21067003802,21067004007,-4.142193,0.159110,0.097361,0.320555,0.087172,0.335802,0,0,50.1,53.182461,10.112343
1,1,21067004007,21067003802,-2.293804,0.086543,0.143814,0.336409,0.160296,0.272938,0,0,41.5,40.567613,40.865849
2,2,21067004007,21067003701,-3.274847,0.082602,0.147529,0.357053,0.147785,0.265031,0,0,42.9,40.034965,55.011505
3,3,21067003701,21067004007,-4.308146,0.157498,0.098955,0.319549,0.086289,0.337710,0,0,50.1,53.182461,10.112343
4,4,21067004207,21067003918,4.302579,0.266098,0.034461,0.475377,0.125374,0.098689,0,0,46.7,50.317125,66.423282

In [20]:
df = pd.merge(pickups, dest_choice, left_on = ['origin'], right_on = ['origin'])
df.head()

,Unnamed: 0_x,origin,AM_PRED_PICKUPS,NT_PRED_PICKUPS,MD_PRED_PICKUPS,PM_PRED_PICKUPS,EV_PRED_PICKUPS,PRED_PICKUPS,NT_PRED_PICKUPS_LOG,AM_PRED_PICKUPS_LOG,...,NT_PROB,AM_PROB,MD_PROB,PM_PROB,EV_PROB,airport,tourist,MEDIAN_AGE,P_BACH_25P,TOTAL_EMP_DEN
0,0,21067000101,115.549482,200.85,365.444593,275.6231,305.226973,1262.694147,5.302558,4.749699,...,0.184512,0.075308,0.333679,0.101089,0.305411,0,0,50.1,53.182461,10.112343
1,0,21067000101,115.549482,200.85,365.444593,275.6231,305.226973,1262.694147,5.302558,4.749699,...,0.108948,0.096245,0.357831,0.201795,0.235181,0,0,41.5,40.567613,40.865849
2,0,21067000101,115.549482,200.85,365.444593,275.6231,305.226973,1262.694147,5.302558,4.749699,...,0.118458,0.084724,0.451270,0.137924,0.207624,0,0,46.7,50.317125,66.423282
3,0,21067000101,115.549482,200.85,365.444593,275.6231,305.226973,1262.694147,5.302558,4.749699,...,0.281451,0.195153,0.355000,0.157842,0.010554,1,0,49.1,50.110497,93.963301
4,0,21067000101,115.549482,200.85,365.444593,275.6231,305.226973,1262.694147,5.302558,4.749699,...,0.237215,0.019308,0.254212,0.118722,0.370543,0,0,48.0,51.208459,70.815127

In [21]:
df = df[['origin', 'destination', 'dest_choice_logsum', 'NT_PRED_PICKUPS_LOG', 'AM_PRED_PICKUPS_LOG', 'MD_PRED_PICKUPS_LOG','PM_PRED_PICKUPS_LOG', 'EV_PRED_PICKUPS_LOG', 'PRED_PICKUPS_LOG', 'airport', 'tourist', 'MEDIAN_AGE', 'P_BACH_25P', 'TOTAL_EMP_DEN', 'NT_PROB', 'AM_PROB', 'MD_PROB', 'PM_PROB', 'EV_PROB']]
df.head()

,origin,destination,dest_choice_logsum,NT_PRED_PICKUPS_LOG,AM_PRED_PICKUPS_LOG,MD_PRED_PICKUPS_LOG,PM_PRED_PICKUPS_LOG,EV_PRED_PICKUPS_LOG,PRED_PICKUPS_LOG,airport,tourist,MEDIAN_AGE,P_BACH_25P,TOTAL_EMP_DEN,NT_PROB,AM_PROB,MD_PROB,PM_PROB,EV_PROB
0,21067000101,21067004007,-1.590537,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,0,50.1,53.182461,10.112343,0.184512,0.075308,0.333679,0.101089,0.305411
1,21067000101,21067003802,1.688342,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,0,41.5,40.567613,40.865849,0.108948,0.096245,0.357831,0.201795,0.235181
2,21067000101,21067003918,1.258695,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,0,46.7,50.317125,66.423282,0.118458,0.084724,0.451270,0.137924,0.207624
3,21067000101,21067004207,4.805035,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,1,0,49.1,50.110497,93.963301,0.281451,0.195153,0.355000,0.157842,0.010554
4,21067000101,21067004006,-2.597019,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,0,48.0,51.208459,70.815127,0.237215,0.019308,0.254212,0.118722,0.370543

In [22]:
## Apply Negative Binomial Model to get pickups
df['NT_PICKUPS'] = np.exp(-1.699553*df['airport'] + 0.5047479*df['tourist'] + 0.3486627*df['NT_PRED_PICKUPS_LOG'] + 1.082214*df['dest_choice_logsum'] - 0.0173114*df['MEDIAN_AGE'] + 0.0170123*df['P_BACH_25P'] + 0.000000716*df['TOTAL_EMP_DEN'] + 0.2991526 - 5.691818)
df['AM_PICKUPS'] = np.exp(-0.7743786*df['airport'] + 0.4779832*df['tourist'] + 0.4050372*df['AM_PRED_PICKUPS_LOG'] + 0.6230226*df['dest_choice_logsum'] - 0.0262*df['MEDIAN_AGE'] + 0.0143772*df['P_BACH_25P']+ 0.000000498*df['TOTAL_EMP_DEN'] + 0.3775664 - 1.946639)
df['MD_PICKUPS'] = np.exp(-0.6405087*df['airport'] + 0.7809523*df['tourist'] + 0.3927277*df['MD_PRED_PICKUPS_LOG'] + 0.6977969*df['dest_choice_logsum'] - 0.0208753*df['MEDIAN_AGE'] + 0.0123951*df['P_BACH_25P']+ 0.00000161*df['TOTAL_EMP_DEN'] + 0.3918755 - 2.551229)
df['PM_PICKUPS'] = np.exp(-0.4855696*df['airport'] + 0.890186*df['tourist'] + 0.4090155*df['PM_PRED_PICKUPS_LOG'] + 0.8352944*df['dest_choice_logsum'] - 0.0216488*df['MEDIAN_AGE'] + 0.0149257*df['P_BACH_25P']+ 0.00000217*df['TOTAL_EMP_DEN'] + 0.363544 - 4.089885)
df['EV_PICKUPS'] = np.exp(0.0188928*df['airport'] + 0.830838*df['tourist'] + 0.3445732*df['EV_PRED_PICKUPS_LOG'] + 0.9817033*df['dest_choice_logsum'] - 0.0215845*df['MEDIAN_AGE'] + 0.0199614*df['P_BACH_25P']+ 0.00000224*df['TOTAL_EMP_DEN'] + 0.4076045 - 5.265743)
df.head()

,origin,destination,dest_choice_logsum,NT_PRED_PICKUPS_LOG,AM_PRED_PICKUPS_LOG,MD_PRED_PICKUPS_LOG,PM_PRED_PICKUPS_LOG,EV_PRED_PICKUPS_LOG,PRED_PICKUPS_LOG,airport,...,NT_PROB,AM_PROB,MD_PROB,PM_PROB,EV_PROB,NT_PICKUPS,AM_PICKUPS,MD_PICKUPS,PM_PICKUPS,EV_PICKUPS
0,21067000101,21067004007,-1.590537,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,...,0.184512,0.075308,0.333679,0.101089,0.305411,0.005366,0.305988,0.262284,0.047481,0.011470
1,21067000101,21067003802,1.688342,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,...,0.108948,0.096245,0.357831,0.201795,0.235181,0.174652,2.465949,2.645548,0.732976,0.268409
2,21067000101,21067003918,1.258695,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,...,0.118458,0.084724,0.451270,0.137924,0.207624,0.118355,1.894282,1.984580,0.529128,0.191169
3,21067000101,21067004207,4.805035,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,1,...,0.281451,0.195153,0.355000,0.157842,0.010554,0.960054,7.448959,11.785926,5.960547,5.988749
4,21067000101,21067004006,-2.597019,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,...,0.237215,0.019308,0.254212,0.118722,0.370543,0.001811,0.167864,0.132499,0.020816,0.004296

In [23]:
#### Apply Probabilities
time_of_day = ["NT", "AM", "MD", "PM", "EV"]
for time in time_of_day:
    df[time + "_TRIPS"] = df[time + "_PICKUPS"] * df[time + "_PROB"]
df.head()

,origin,destination,dest_choice_logsum,NT_PRED_PICKUPS_LOG,AM_PRED_PICKUPS_LOG,MD_PRED_PICKUPS_LOG,PM_PRED_PICKUPS_LOG,EV_PRED_PICKUPS_LOG,PRED_PICKUPS_LOG,airport,...,NT_PICKUPS,AM_PICKUPS,MD_PICKUPS,PM_PICKUPS,EV_PICKUPS,NT_TRIPS,AM_TRIPS,MD_TRIPS,PM_TRIPS,EV_TRIPS
0,21067000101,21067004007,-1.590537,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,...,0.005366,0.305988,0.262284,0.047481,0.011470,0.000990,0.023043,0.087519,0.004800,0.003503
1,21067000101,21067003802,1.688342,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,...,0.174652,2.465949,2.645548,0.732976,0.268409,0.019028,0.237334,0.946659,0.147911,0.063125
2,21067000101,21067003918,1.258695,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,...,0.118355,1.894282,1.984580,0.529128,0.191169,0.014020,0.160490,0.895582,0.072979,0.039691
3,21067000101,21067004207,4.805035,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,1,...,0.960054,7.448959,11.785926,5.960547,5.988749,0.270208,1.453685,4.184008,0.940822,0.063206
4,21067000101,21067004006,-2.597019,5.302558,4.749699,5.901115,5.619034,5.721056,7.141003,0,...,0.001811,0.167864,0.132499,0.020816,0.004296,0.000429,0.003241,0.033683,0.002471,0.001592

In [25]:
neg_bin_pred_trips = df[['origin', 'destination', 'NT_TRIPS', 'AM_TRIPS', 'MD_TRIPS', 'PM_TRIPS', 'EV_TRIPS']]
neg_bin_pred_trips.to_csv('Cleaned_Inputs/Intermediate/neg_bin_pred_trips.csv', index = False)

In [29]:
neg_bin_pred_trips[['NT_TRIPS', 'AM_TRIPS', 'MD_TRIPS', 'PM_TRIPS', 'EV_TRIPS']].sum()

NT_TRIPS      874.178096
AM_TRIPS     2640.545759
MD_TRIPS    13660.046446
PM_TRIPS     2488.412405
EV_TRIPS     1522.559140
dtype: float64

In [30]:
neg_bin_pred_trips[['NT_TRIPS', 'AM_TRIPS', 'MD_TRIPS', 'PM_TRIPS', 'EV_TRIPS']].sum().sum()

21185.741845450066